### ISSUE TITLE
Login to tv.apple.com not possible

### ISSUE THREAD

**Issue by bcutter** [airtower-luna/referer-mod#108]
Using

```
{
  "any": {
    "action": "remove",
    "referer": ""
  },
  "same": {
    "action": "keep",
    "referer": ""
  },
  "domains": []
}
```

does not allow to log in at https://tv.apple.com. After entering the mail address, the field for entering the password will never show up.

If the extension is disabled, it works without any issue.

How to whitelist this use-case?

**Comment by bcutter** [comment]
I thought it would work with

```
{
  "any": {
    "action": "remove",
    "referer": ""
  },
  "same": {
    "action": "keep",
    "referer": ""
  },
  "domains": [
    {
      "domain": "idmsa.apple.com",
      "action": "keep",
      "referer": "",
      "origin": "tv.apple.com"
    }
  ]
}
```

as I could login once. After trying it again I now only get

![grafik](https://github.com/airtower-luna/referer-mod/assets/13799156/1c6567ad-13fe-4a3a-a3ed-17b7aff59e83)

**Comment by airtower-luna** [comment]
I'm not familiar with Apple services, so I can't say exactly how the rule would need to look. If that rule worked once and then not and now it doesn't matter if you disable the add-on it could be that there's another (additional) issue. Or that there's some caching issue or stored state (cookie, etc.) that keeps causing trouble.

If you want to make a very broad rule that keeps the `Referer` for requests between all `apple.com` subdomains, you'd need to set domain *and* origin to `apple.com`. `<SAME>` only applies within the *exact* domain, while a domain-specific rule covers subdomains. But again, I can't say if that'd help because I don't known those services, you'd have to check what requests actually happen and which fail (e.g. using developer tools).

**Comment by bcutter** [comment]
It was a server-side blocking due to too many login attempts. Using this works just fine (meaning: login possible without any issues).

![grafik](https://github.com/airtower-luna/referer-mod/assets/13799156/4ec149a7-8d4e-4626-93f6-78e2da9c2a36)

Unfortunately I run into more and more issues caused by this addon recently. E. g. on www.lenovo.com certain elements do not load until this is set:
![grafik](https://github.com/airtower-luna/referer-mod/assets/13799156/11430104-cc11-49dd-815a-e43397e8fcb8)

So whenever a website does not behave or look like it should, now this addon is on top of my suspicious list (which was always right in the last weeks).

Feel free to close this issue.

**Comment by airtower-luna** [comment]
Thanks for the update, glad you got it working! :slightly_smiling_face:
