### ISSUE TITLE
Does it work with the JavaScript document.referrer ?

### ISSUE THREAD

**Issue by Joel889** [airtower-luna/referer-mod#5]
Out of curiosity, does the addon also modify the JavaScript document.referrer ?
The other [Referrer](https://addons.mozilla.org/en-US/firefox/addon/referercontrol/) addon supposedly does, in case you are wondering how it can be done.

**Comment by airtower-luna** [comment]
I haven't looked into checking/changing that, but patches to do so would be welcome.

**Comment by kevinoid** [comment]
I just investigated this issue a bit.  The referrer changes from this add-on do not currently affect `document.referrer` due to [Mozilla Issue #1601496](https://bugzilla.mozilla.org/1601496).

[Referer Control](https://addons.mozilla.org/en-US/firefox/addon/referercontrol/) works around this by adding `<meta name="referrer" content="no-referrer" />` to every page which matches a defined source URL (as described in https://github.com/uBlockOrigin/uMatrix-issues/issues/78#issuecomment-461050262).  This makes `document.referrer` blank when navigating from the modified page (subject to several assumptions/limitations).

[Smart Referer](https://addons.mozilla.org/en-US/firefox/addon/smart-referer/) worked around the issue in [smart-referer/smart-referer@d12e37c8](https://gitlab.com/smart-referer/smart-referer/-/commit/d12e37c8007e2fad75364cb07591c18241160994) with a content script which sets `document.referrer` to the one from its policy at `document_start`.

**Comment by airtower-luna** [comment]
@kevinoid, thank you very much for your research! I think a workaround in the style that Smart Referer uses makes sense here, unless Mozilla releases a fix first.

**Comment by Gitoffthelawn** [comment]
My experience with Mozilla is to never wait for them to fix an issue.  They now have unresolved issues likely older than some of their developers!

**Comment by airtower-luna** [comment]
I finally had time to look into this. Expect a release soon-ish, but I'd appreciate testing in the meantime. :slightly_smiling_face:

**Comment by Gitoffthelawn** [comment]
I have a queue of software and hardware I have been asked to test.  I have added this project to the queue.  I don't expect to have time very soon, but I will make an effort to squeeze this in during some free time.

I had some good test sites for this issue, but they are now defunct.  Who can mention some reliable test sites?

**Comment by airtower-luna** [comment]
Thank you! I've mostly used https://browserleaks.com/javascript as mentioned in that Firefox bug.

**Comment by Gitoffthelawn** [comment]
You're welcome!  Thank *you* for the code enhancement!

That site is one of the few remaining test sites I have as well.  Unfortunately, it doesn't show the non-JS referer on the same page, which makes testing a little more cumbersome. 

If you, or anyone else, finds any other good tests, please do post them here.  Note that some of the test sites out there do *not* provide accurate results.

**Comment by airtower-luna** [comment]
I have been thinking of setting up a Docker-based test environment. Shouldn't be too hard, a simple CGI script that returns the Referer and includes a script to show `document.referrer`. I was mostly thinking of that in terms of implementing automated tests, but if anyone is interested in that I might just do the Docker part and push that to a branch until actual tests are ready.

**Comment by Gitoffthelawn** [comment]
That sounds great.  You can likely host it on GitHub pages to keep it free and easy.

**Comment by airtower-luna** [comment]
Pages don't support dynamic content unfortunately, but I hope the environment in [`testserver/`](https://github.com/airtower-luna/referer-mod/tree/master/testserver) will be easy enough to use. It already works for [automated tests](https://github.com/airtower-luna/referer-mod/blob/master/test.py), so there's that. And I wouldn't mind if anyone wanted to host the test server publicly. :slightly_smiling_face:
