### ISSUE TITLE
Could not download for Android

### ISSUE THREAD

**Issue by Ryakna** [airtower-luna/referer-mod#8]
Always used the add-on on PC and phone but now I'm unable to download it on Android. It says "This add-on is not available on your platform."
Is this by design?

I'm gonna try to install the xpi directly.

**Comment by airtower-luna** [comment]
The only restriction should be the min version in the `applications` field of [manifest.json](https://github.com/airtower-luna/referer-mod/blob/master/manifest.json). Which seems to have been renamed to [`browser_specific_settings`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings) since I last touched the code. Do you have any debug info that might indicate if that's the problem?

**Comment by airtower-luna** [comment]
Please test version 0.7 and let me know if it works!

**Comment by Ryakna** [comment]
The previous version worked well if I installed the xpi file directly on the device, but did not if you tried to install via the add-ons website. Also the add-on didn't show after searching on the mobile site.

After 0.7 it shows in search again and let's you install on Android, so that was the problem.

Thanks.
